spring:
  application:
    name: authService
  thymeleaf:
    # disable templates (.html)
    check-template-location: false
  datasource:
    enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
  jwt:
    secret: ${JWT_SECRET}
    # tokens set to 0 to allow never expiring JWT tokens
    accessTokenExpiration: 0 # 30 minutes in seconds: 1800
    refreshTokenExpiration: 0 # 7 days in seconds: 604700
  profiles:
    # profile can be set using a default springboot environment: SPRING_PROFILES_ACTIVE
    active: dev
  # Table record limits (See: TableLimitConfig class and MaxTableSizeAspect)
  limits:
    profile: 20
    user: 20
    address: 20

swaggerUseSSL: false

# cerbos policies
policy-service:
  base-url: ${POLICY_SERVICE_URL}